travis:
  secure:
    BINSTAR_TOKEN: mmxy9crF307Cb84eF1fYzKE9oSmihMAzlDdbuW4KUigPxpR5bjSIUF0k8/s9NczSOiwYkfF8VhFOjNp/Wq7IC1lF6ka+No76Sb92rAHJvUoFJUl1jD2tawEes0qHgpAA7QuIyJrIrfqB95dxAayoUmO+dPy6CSkorDqbDT1CS/kOe8sIgVi6nCLsxTIXL8b0QTuodNnoHlkEQoZcElDLjwePewCMnbzRoLwDr6/WqccpBwOnzo7WI2hf5p+M5+nueS8++LnXWugU4l6VU44UMMSu1VONTfUVMyC48KRALwXnNlfqYukOtR8wmjom43EG2oxzmXMl16c1kCpyLG0VVA6hYh5isgVzKLzMx/TNNsX7w4gWT/c+wH70xpKReTJtHYJWRWgyl2Y6Z8fn7xjYF5cKdnOfcTJpYszYg+HEoWehLc9rBAitZnHxGUC1xspUXyAK2iWgflZKojEsn0USvHwZikhzltDxxTO5fD7x+QcYZNzolubSv0auBqim62TDSFMubVOHpfm6mSZaNqsRo6KybEUI+sn6oXvWsnmb3iIdVJSCFfUG/37aqrd1z8vYKaGc7oDwuCS2nD6HiQnV0Jgqq+nfcXMpy1f1hhL03dCFu6v+yzIkg1k0lr68YUw5/uw5xCtnkdyXneAZo/K9biEmEvRlCTgGQx2TMvI4sT4=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
